"""Generate reliefo configs for the main Veracruz municipios, in importance
order. Fetches each municipio boundary from OSM/Nominatim, computes a framed
bbox, and writes examples/<slug>.toml (5 m LiDAR, auto-discovered charts, bare
relief). Run:  uv run python scripts/veracruz_batch.py
"""
from __future__ import annotations

import json
import time
import unicodedata
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[1]
BND = ROOT / "data" / "boundaries"
EX = ROOT / "examples"
UA = "reliefo/0.2 (relief poster generator; muxxeroerty@gmail.com)"
NOMINATIM = "https://nominatim.openstreetmap.org/search"

DENUE_CSV = ("/home/ieqr/Desktop/research/denue_xalapa/data/"
             "conjunto_de_datos/denue_inegi_30_.csv")
# DENUE municipio code per city (for zone labels)
CVEMUN = {
    "Córdoba": "044", "Orizaba": "118", "Coatzacoalcos": "039", "Poza Rica": "131",
    "Boca del Río": "028", "Minatitlán": "108", "Tuxpan": "189",
    "San Andrés Tuxtla": "141", "Papantla": "124", "Coatepec": "038",
    "Perote": "128", "Catemaco": "032", "Huatusco": "071", "Zongolica": "201",
    "Xico": "092",
}

# (display name, Nominatim query, poster title) — IMPORTANCE ORDER
# (Veracruz port is omitted: no clean OSM municipio polygon, and the name is
#  reserved for the whole-state map, examples/veracruz.toml.)
CITIES = [
    ("Córdoba",            "Córdoba, Veracruz, Mexico",               "CÓRDOBA"),
    ("Orizaba",            "Orizaba, Veracruz, Mexico",               "ORIZABA"),
    ("Coatzacoalcos",      "Coatzacoalcos, Veracruz, Mexico",         "COATZACOALCOS"),
    ("Poza Rica",          "Poza Rica de Hidalgo, Veracruz, Mexico",  "POZA RICA"),
    ("Boca del Río",       "Boca del Río, Veracruz, Mexico",          "BOCA DEL RÍO"),
    ("Minatitlán",         "Minatitlán, Veracruz, Mexico",            "MINATITLÁN"),
    ("Tuxpan",             "Tuxpan, Veracruz, Mexico",                "TUXPAN"),
    ("San Andrés Tuxtla",  "San Andrés Tuxtla, Veracruz, Mexico",     "SAN ANDRÉS TUXTLA"),
    ("Papantla",           "Papantla, Veracruz, Mexico",              "PAPANTLA"),
    ("Coatepec",           "Coatepec, Veracruz, Mexico",              "COATEPEC"),
    ("Perote",             "Perote, Veracruz, Mexico",                "PEROTE"),
    ("Catemaco",           "Catemaco, Veracruz, Mexico",              "CATEMACO"),
    ("Huatusco",           "Huatusco, Veracruz, Mexico",              "HUATUSCO"),
    ("Zongolica",          "Zongolica, Veracruz, Mexico",             "ZONGOLICA"),
    ("Xico",               "Xico, Veracruz, Mexico",                  "XICO"),
]


def slugify(name: str) -> str:
    s = unicodedata.normalize("NFKD", name)
    s = "".join(c for c in s if not unicodedata.combining(c))
    return "".join(c if c.isalnum() else "_" for c in s.lower()).strip("_")


def fetch_boundary(query: str) -> dict | None:
    """Return the best municipio (admin) polygon GeoJSON geometry, or None."""
    r = httpx.get(NOMINATIM, headers={"User-Agent": UA}, timeout=60.0, params={
        "q": query, "format": "jsonv2", "polygon_geojson": 1,
        "limit": 8, "countrycodes": "mx", "addressdetails": 1})
    r.raise_for_status()
    best = None
    for res in r.json():
        g = res.get("geojson", {})
        if g.get("type") not in ("Polygon", "MultiPolygon"):
            continue
        if res.get("category") != "boundary" or res.get("type") != "administrative":
            continue
        bb = [float(v) for v in res["boundingbox"]]      # [s, n, w, e]
        span = max(bb[1] - bb[0], bb[3] - bb[2])
        if span > 1.2:                                   # too big -> the state
            continue
        cand = (span, g, res.get("display_name", ""))
        if best is None or cand[0] < best[0]:            # smallest reasonable
            best = cand
    return None if best is None else {"geom": best[1], "name": best[2], "span": best[0]}


def bbox_of(geom: dict, margin_frac: float = 0.06, margin_min: float = 0.01):
    xs, ys = [], []

    def walk(c):
        if c and isinstance(c[0], (int, float)):
            xs.append(c[0]); ys.append(c[1])
        else:
            for x in c:
                walk(x)
    walk(geom["coordinates"])
    w, s, e, n = min(xs), min(ys), max(xs), max(ys)
    mx = max((e - w) * margin_frac, margin_min)
    my = max((n - s) * margin_frac, margin_min)
    w, s, e, n = w - mx, s - my, e + mx, n + my
    # cap each dimension so giant rural municipios stay tractable + city-focused
    # (the boundary mask is clipped to this window; big ones become urban crops)
    cap = 0.34
    cx, cy = (w + e) / 2, (s + n) / 2
    if e - w > cap:
        w, e = cx - cap / 2, cx + cap / 2
    if n - s > cap:
        s, n = cy - cap / 2, cy + cap / 2
    return round(w, 5), round(s, 5), round(e, 5), round(n, 5)


TOML = """# {disp} — generated by scripts/veracruz_batch.py (importance order #{i})
[paths]
data = "../data/{slug}"
out  = "../output"

[map]
name     = "{disp}"
slug     = "{slug}"
title    = "{title}"
subtitle = "VERACRUZ · MÉXICO"
bbox     = {{ west = {w}, south = {s}, east = {e}, north = {n} }}

[boundary]
file = "../data/boundaries/{slug}_mun.geojson"

[dem]
source = "lidar"      # INEGI 5 m terrain; charts auto-discovered from the bbox
res_m  = 5

[relief]
palette = "oslo"

[streets]
enabled  = true
osm_file = "../data/mexico.osm.pbf"

[labels]
enabled   = true
source    = "denue"
cvemun    = "{cvemun}"
denue_csv = "{denue}"

[render]
resolution = 4000
samples    = 160
"""


def main():
    BND.mkdir(parents=True, exist_ok=True)
    print(f"{'#':>2}  {'city':18}  {'slug':18}  {'span°':>6}  bbox / status")
    for i, (disp, query, title) in enumerate(CITIES, 1):
        slug = slugify(disp)
        try:
            b = fetch_boundary(query)
        except Exception as ex:                          # noqa: BLE001
            print(f"{i:>2}  {disp:18}  {slug:18}  {'':>6}  ERROR {ex}")
            time.sleep(1.2)
            continue
        if b is None:
            print(f"{i:>2}  {disp:18}  {slug:18}  {'':>6}  NO POLYGON FOUND")
            time.sleep(1.2)
            continue
        feat = {"type": "Feature", "properties": {"name": disp}, "geometry": b["geom"]}
        (BND / f"{slug}_mun.geojson").write_text(
            json.dumps({"type": "FeatureCollection", "features": [feat]}))
        w, s, e, n = bbox_of(b["geom"])
        (EX / f"{slug}.toml").write_text(TOML.format(
            disp=disp, slug=slug, title=title, i=i, w=w, s=s, e=e, n=n,
            cvemun=CVEMUN.get(disp, ""), denue=DENUE_CSV))
        print(f"{i:>2}  {disp:18}  {slug:18}  {b['span']:.3f}  "
              f"[{w},{s},{e},{n}]")
        time.sleep(1.2)                                  # Nominatim etiquette


if __name__ == "__main__":
    main()
